name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag caroga/commentoplusplus:latest

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
    - name: Tag the image
      run: docker tag caroga/commentoplusplus:latest caroga/commentoplusplus:"$TAG"
      env:
        TAG: ${{ github.event.release.tag_name }}
        
    - name: Push the image to Docker Hub
      run: docker push caroga/commentoplusplus:latest && docker push caroga/commentoplusplus:"$TAG"
      env:
        TAG: ${{ github.event.release.tag_name }}
